[package]
name = "my_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[definitions]
futures = "0.3"

[dependencies]
futures = "0.3.26"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]

